// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-02-13 00:17:08
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Order is the golang structure of table order for DAO operations like Where/Data.
type Order struct {
	g.Meta  `orm:"table:order, do:true"`
	Id      interface{} //
	Uid     interface{} //
	OrderId interface{} //
	Time    *gtime.Time //
}
