// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-02-13 00:17:08
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta `orm:"table:user, do:true"`
	Id     interface{} //
	Name   interface{} //
	Age    interface{} //
}
