// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-02-13 00:17:08
// =================================================================================

package entity

// User is the golang structure for table user.
type User struct {
	Id   uint   `json:"id"   ` //
	Name string `json:"name" ` //
	Age  int    `json:"age"  ` //
}
